// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Tuna.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace eval::tuna;

class TunaHandler : virtual public TunaIf {
 public:
  TunaHandler() {
    // Your initialization goes here
  }

  bool ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void simpleQuery(simpleQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("simpleQuery\n");
  }

  void doubleQuery(doubleQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("doubleQuery\n");
  }

  void fullQuery(fullQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("fullQuery\n");
  }

  void reserveFrom(simpleQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("reserveFrom\n");
  }

  void reserve(const std::vector<int32_t> & ids) {
    // Your implementation goes here
    printf("reserve\n");
  }

  bool destroy(const int32_t id) {
    // Your implementation goes here
    printf("destroy\n");
  }

  void getTask(eval::model::Task& _return, const int32_t id) {
    // Your implementation goes here
    printf("getTask\n");
  }

  void getTasks(std::vector<eval::model::Task> & _return, const std::vector<int32_t> & ids) {
    // Your implementation goes here
    printf("getTasks\n");
  }

  void getTasksFrom(std::vector<eval::model::Task> & _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("getTasksFrom\n");
  }

  bool updateTask(const eval::model::Task& task) {
    // Your implementation goes here
    printf("updateTask\n");
  }

  int32_t insertTask(const eval::model::Task& task) {
    // Your implementation goes here
    printf("insertTask\n");
  }

  void getTestCase(eval::model::TestCase& _return, const int32_t id) {
    // Your implementation goes here
    printf("getTestCase\n");
  }

  void getTestCases(std::vector<eval::model::TestCase> & _return, const std::vector<int32_t> & ids) {
    // Your implementation goes here
    printf("getTestCases\n");
  }

  void getTestCasesFrom(std::vector<eval::model::TestCase> & _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("getTestCasesFrom\n");
  }

  bool updateTestCase(const eval::model::TestCase& test_case) {
    // Your implementation goes here
    printf("updateTestCase\n");
  }

  int32_t insertTestCase(const eval::model::TestCase& test_case) {
    // Your implementation goes here
    printf("insertTestCase\n");
  }

  void getSubmission(eval::model::Submission& _return, const int32_t id) {
    // Your implementation goes here
    printf("getSubmission\n");
  }

  void getSubmissions(std::vector<eval::model::Submission> & _return, const std::vector<int32_t> & ids) {
    // Your implementation goes here
    printf("getSubmissions\n");
  }

  void getSubmissionsFrom(std::vector<eval::model::Submission> & _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("getSubmissionsFrom\n");
  }

  bool updateSubmission(const eval::model::Submission& submission) {
    // Your implementation goes here
    printf("updateSubmission\n");
  }

  int32_t insertSubmission(const eval::model::Submission& submission) {
    // Your implementation goes here
    printf("insertSubmission\n");
  }

  void getJob(eval::model::Job& _return, const int32_t id) {
    // Your implementation goes here
    printf("getJob\n");
  }

  void getJobs(std::vector<eval::model::Job> & _return, const std::vector<int32_t> & ids) {
    // Your implementation goes here
    printf("getJobs\n");
  }

  void getJobsFrom(std::vector<eval::model::Job> & _return, const std::string& qname, const std::vector<std::string> & data) {
    // Your implementation goes here
    printf("getJobsFrom\n");
  }

  bool updateJob(const eval::model::Job& job) {
    // Your implementation goes here
    printf("updateJob\n");
  }

  int32_t insertJob(const eval::model::Job& job) {
    // Your implementation goes here
    printf("insertJob\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TunaHandler> handler(new TunaHandler());
  shared_ptr<TProcessor> processor(new TunaProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

