// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Tuna.h"
#include <tuna.h>
#include <server/TThreadedServer.h>
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace eval::tuna;

class TunaHandler : virtual public TunaIf {

 private:
  Tuna T_;
 public:
  TunaHandler() {
    // Your initialization goes here
  }

  bool ping() {
    return true;
    printf("ping\n");
  }

  void simpleQuery(simpleQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.simpleQuery(qname, data);
    printf("simpleQuery\n");
  }

  void doubleQuery(doubleQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.doubleQuery(qname, data);
    printf("doubleQuery\n");
  }

  void fullQuery(fullQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.fullQuery(qname, data);
    printf("fullQuery\n");
  }

  void reserveFrom(simpleQ& _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.reserveFrom(qname, data);
    printf("reserveFrom\n");
  }

  void reserve(const std::vector<int32_t> & ids) {
    T_.reserve(ids);
    printf("reserve\n");
  }

  bool destroy(const int32_t id) {
    return T_.destroy(id);
    printf("destroy\n");
  }

  void getTask(eval::model::Task& _return, const int32_t id) {
    vector<eval::model::Task> sol =
      T_.multiGet<eval::model::Task>(vector<object_id> (1,id));

    _return = sol.size() ? sol.at(0) : eval::model::Task();
    printf("getTask\n");
  }

  void getTasks(std::vector<eval::model::Task> & _return, const std::vector<int32_t> & ids) {
    _return = T_.multiGet<eval::model::Task>(ids);
    printf("getTasks\n");
  }

  void getTasksFrom(std::vector<eval::model::Task> & _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.getFrom<eval::model::Task>(qname, data);
    printf("getTasksFrom\n");
  }

  bool updateTask(const eval::model::Task& task) {
    return T_.update("tasks", serialize(task)); 
    printf("updateTask\n");
  }

  int32_t insertTask(const eval::model::Task& task) {
    return T_.insert("tasks", serialize(task)); 
    printf("insertTask\n");
  }

  void getTestCase(eval::model::TestCase& _return, const int32_t id) {
    vector<eval::model::TestCase> sol =
      T_.multiGet<eval::model::TestCase>(vector<object_id> (1,id));

    _return = sol.size() ? sol.at(0) : eval::model::TestCase();
    printf("getTestCase\n");
  }

  void getTestCases(std::vector<eval::model::TestCase> & _return, const std::vector<int32_t> & ids) {
    _return = T_.multiGet<eval::model::TestCase>(ids);
    printf("getTestCases\n");
  }

  void getTestCasesFrom(std::vector<eval::model::TestCase> & _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.getFrom<eval::model::TestCase>(qname, data);
    printf("getTestCasesFrom\n");
  }

  bool updateTestCase(const eval::model::TestCase& test_case) {
    return T_.update("test_cases", serialize(test_case)); 
    printf("updateTestCase\n");
  }

  int32_t insertTestCase(const eval::model::TestCase& test_case) {
    return T_.insert("test_cases", serialize(test_case)); 
    printf("insertTestCase\n");
  }

  void getSubmission(eval::model::Submission& _return, const int32_t id) {
    vector<eval::model::Submission> sol =
      T_.multiGet<eval::model::Submission>(vector<object_id> (1,id));

    _return = sol.size() ? sol.at(0) : eval::model::Submission();
    printf("getSubmission\n");
  }

  void getSubmissions(std::vector<eval::model::Submission> & _return, const std::vector<int32_t> & ids) {
    _return = T_.multiGet<eval::model::Submission>(ids);
    printf("getSubmissions\n");
  }

  void getSubmissionsFrom(std::vector<eval::model::Submission> & _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.getFrom<eval::model::Submission>(qname, data);
    printf("getSubmissionsFrom\n");
  }

  bool updateSubmission(const eval::model::Submission& submission) {
    return T_.update("submissions", serialize(submission)); 
    printf("updateSubmission\n");
  }

  int32_t insertSubmission(const eval::model::Submission& submission) {
    return T_.insert("submissions", serialize(submission)); 
    printf("insertSubmission\n");
  }

  void getJob(eval::model::Job& _return, const int32_t id) {
    vector<eval::model::Job> sol =
      T_.multiGet<eval::model::Job>(vector<object_id> (1,id));

    _return = sol.size() ? sol.at(0) : eval::model::Job();
    printf("getJob\n");
  }

  void getJobs(std::vector<eval::model::Job> & _return, const std::vector<int32_t> & ids) {
    _return = T_.multiGet<eval::model::Job>(ids);
    printf("getJobs\n");
  }

  void getJobsFrom(std::vector<eval::model::Job> & _return, const std::string& qname, const std::vector<std::string> & data) {
    _return = T_.getFrom<eval::model::Job>(qname, data);
    printf("getJobsFrom\n");
  }

  bool updateJob(const eval::model::Job& job) {
    return T_.update("jobs", serialize(job)); 
    printf("updateJob\n");
  }

  int32_t insertJob(const eval::model::Job& job) {
    return T_.insert("jobs", serialize(job)); 
    printf("insertJob\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  if (argc == 2) {
    port = atoi(argv[1]);
    printf("using port %d\n", port); 
  } else {
    printf("using default port %d\n", port); 
  }
  shared_ptr<TunaHandler> handler(new TunaHandler());
  shared_ptr<TProcessor> processor(new TunaProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());
  /*

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  */
 
  TThreadedServer th_server(processor, serverTransport, transportFactory, protocolFactory);
  th_server.serve();

  return 0;
}

