#!/bin/bash

echo 'starting tuna service...'

if [ $# -eq 0 ]; then
  _gen/bin/tnserver &> /tmp/tuna_log &

  echo 'output is redirected to /tmp/tuna_log.'
  echo '"make stop" to stop the service.'

  exit 0
fi

_gen/bin/tnserver


