#!/bin/bash

bin_name="tnserver"

pid=`ps -a | grep $bin_name | cut -b -6`

ps -a | grep $bin_name > /dev/null

if [ $? -eq 0 ]; then
  echo 'stoping tuna service...'
  kill -15 $pid 
else
  echo 'tuna service not running.'
fi
