#!/bin/sh

dir=`pwd | sed 's/\(.*\)\/eval2.*/\1\/eval2/'`
cppfiles=`git diff HEAD HEAD^ --name-only | egrep '\.(cpp|cc|h|hpp)'`
cpp_log=$dir/logs/cpp_lint.log
linted=0

if [ -n "$cppfiles" ]
then
    echo $cppfiles | xargs $dir/bin/cpplint 2>$cpp_log
    if [ $? -ne 0 ]
    then
        echo "[WARNING] Lint failed! Please see $cpp_log for details"
    else
        echo "[SUCCESS] No Lint errors! Keep up the good work!"
    fi
    linted=1
fi

if [ $linted -eq 0 ]
then
    echo "[SUCCESS] Nothing to lint!"
fi

echo
